# Generated by Django 3.2 on 2022-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_delete_review'),
        ('listing', '0003_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('star_rating', models.IntegerField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
