# Generated by Django 3.2 on 2022-08-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20220827_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='star_rating',
        ),
    ]
